name: Clean Architecture With NestJS CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, develop]

jobs:
  continuous-integration:
    uses: codekoller/workflow-templates/.github/workflows/codekoller-ci.yml@main
